version: '3.9'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis-server
    ports:
      - "6379:6379"
